### ISSUE TITLE
ibflex.parser.FlexParserError: OpenPosition has no attribute 'figi'

### ISSUE THREAD

**Issue by hermanmak** [agusalex/ghostfolio-sync#9]
Just finished setting this up, it seems that an empty figi value causes some issue. I took a quick look at my portfolio and it seems Canadian stocks have a figi="".

<img width="805" alt="image" src="https://github.com/agusalex/ghostfolio-sync/assets/6619094/d2197d90-1a24-4c8d-be33-b0a058f1bcb8">

Would this be the upstream influx or this repo?

Thanks!

**Comment by agusalex** [comment]
Sorry for the delay, I see that you fired a ticket to Csingley's ibflex that's the right place to ask. The problem is that it's not easy to replicate the issue unless you try it, debug, and fix it with your account as Csingley pointed out.
Once you have a working version of it let me know and I'll merge it.

**Comment by alishafique1** [comment]
@hermanmak Did you figure this out?

**Comment by snhuber** [comment]
You can just deselect the column in the IB Flex attributes for open positions, trades, and cash transactions.
